name: Build and test go project

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run build
        run: go build -v main.go

      - name: Run tests
        run: go test